config/routes.rb
Rails.application.routes.draw do
  get "search/index"
  resources :dog_ownerships
  resources :cat_ownerships
  resources :vets
  resources :owners
  resources :dogs
  resources :cats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'search', to: 'search#index', as: 'search'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/dog_ownership.rb
class DogOwnership < ApplicationRecord
  belongs_to :dog
  belongs_to :owner
  validates :dog_id, presence: true
  validates :owner_id, presence: true
end

app/controllers/dog_ownerships_controller.rb
class DogOwnershipsController < ApplicationController
  before_action :set_dog_ownership, only: %i[ show edit update destroy ]

  # GET /dog_ownerships or /dog_ownerships.json
  def index
    @dog_ownerships = DogOwnership.all
  end

  # GET /dog_ownerships/1 or /dog_ownerships/1.json
  def show
    @dog_ownerships = DogOwnership.find(params[:id])
  end

  # GET /dog_ownerships/new
  def new
    @dog_ownership = DogOwnership.new
  end

  # GET /dog_ownerships/1/edit
  def edit
  end

  # POST /dog_ownerships or /dog_ownerships.json
  def create
    @dog_ownership = DogOwnership.new(dog_ownership_params)

    respond_to do |format|
      if @dog_ownership.save
        format.html { redirect_to @dog_ownership, notice: "Dog ownership was successfully created." }
        format.json { render :show, status: :created, location: @dog_ownership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dog_ownership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dog_ownerships/1 or /dog_ownerships/1.json
  def update
    respond_to do |format|
      if @dog_ownership.update(dog_ownership_params)
        format.html { redirect_to @dog_ownership, notice: "Dog ownership was successfully updated." }
        format.json { render :show, status: :ok, location: @dog_ownership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dog_ownership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dog_ownerships/1 or /dog_ownerships/1.json
  def destroy
    @dog_ownership.destroy!

    respond_to do |format|
      format.html { redirect_to dog_ownerships_path, status: :see_other, notice: "Dog ownership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog_ownership
      @dog_ownership = DogOwnership.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dog_ownership_params
      params.require(:dog_ownership).permit(:dog_id, :owner_id)
    end
end

app/helpers/dog_ownerships_helper.rb
module DogOwnershipsHelper
end

app/views/dog_ownerships/_dog_ownership.html.erb
<div id="<%= dom_id dog_ownership %>">
  <p>
    <strong>Dog:</strong>
    <%= dog_ownership.dog_id %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= dog_ownership.owner_id %>
  </p>

</div>

app/views/dog_ownerships/_form.html.erb
<%= form_with(model: dog_ownership) do |form| %>
  <% if dog_ownership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dog_ownership.errors.count, "error") %> prohibited this dog_ownership from being saved:</h2>

      <ul>
        <% dog_ownership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :dog_id, style: "display: block" %>
    <%= form.text_field :dog_id %>
  </div>

  <div>
    <%= form.label :owner_id, style: "display: block" %>
    <%= form.text_field :owner_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dog_ownerships/edit.html.erb
<% content_for :title, "Editing dog ownership" %>

<h1>Editing dog ownership</h1>

<%= render "form", dog_ownership: @dog_ownership %>

<br>

<div>
  <%= link_to "Show this dog ownership", @dog_ownership %> |
  <%= link_to "Back to dog ownerships", dog_ownerships_path %>
</div>

app/views/dog_ownerships/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Dog ownerships" %>

<h1>Dog ownerships</h1>

<div id="dog_ownerships">
  <% @dog_ownerships.each do |dog_ownership| %>
    <%= render dog_ownership %>
    <p>
      <%= link_to "Show this dog ownership", dog_ownership %>
    </p>
  <% end %>
</div>

app/views/dog_ownerships/new.html.erb
<% content_for :title, "New dog ownership" %>

<h1>New dog ownership</h1>

<%= render "form", dog_ownership: @dog_ownership %>

<br>

<div>
  <%= link_to "Back to dog ownerships", dog_ownerships_path %>
</div>

app/views/dog_ownerships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dog_ownership %>

<div>
  <%= link_to "Edit this dog ownership", edit_dog_ownership_path(@dog_ownership) %> |
  <%= link_to "Back to dog ownerships", dog_ownerships_path %>

  <%= button_to "Destroy this dog ownership", @dog_ownership, method: :delete %>
</div>