config/routes.rb
Rails.application.routes.draw do
  get "search/index"
  resources :dog_ownerships
  resources :cat_ownerships
  resources :vets
  resources :owners
  resources :dogs
  resources :cats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'search', to: 'search#index', as: 'search'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Intro" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid d-flex justify-content-between align-items-center">
        <a class="navbar-brand" href="/">Intro Project</a>
        <ul class="navbar-nav flex-row">
          <li class="nav-item px-3">
            <%= link_to "About", about_path, class: "nav-link text-dark text-decoration-none" %>
          </li>
          <li class="nav-item px-3">
            <%= link_to "Search", search_path, class: "nav-link text-dark text-decoration-none" %>
          </li>
          <li class="nav-item px-3">
            <%= link_to "Cats", cats_path, class: "nav-link text-dark text-decoration-none" %>
          </li>
          <li class="nav-item px-3">
            <%= link_to "Dogs", dogs_path, class: "nav-link text-dark text-decoration-none" %>
          </li>
          <li class="nav-item px-3">
            <%= link_to "Owners", owners_path, class: "nav-link text-dark text-decoration-none" %>
          </li>
          <li class="nav-item px-3">
            <%= link_to "Vets", vets_path, class: "nav-link text-dark text-decoration-none" %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>